
version: "2.1"

services:
  dps_integration:
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/dps-integration:latest
    volumes:
      - /etc/opt/ericsson/ERICmodeldeployment/data
      - /etc/opt/ericsson/ERICmodeldeployment/models

  postgres:
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/postgres:latest

  jboss:
    links:
      - postgres:postgresql-server
      - dps_integration:db1-service
    build: src/test/docker/jboss
    volumes:
    - ./src/test/docker/jboss/config:/opt/ericsson/docker/config
    volumes_from:
      - dps_integration
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g
    ports:
      - "9999:9999"
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"

  netsim:
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/netsim_v2:17.9
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    cap_add:
      - NET_ADMIN
    network_mode: "service:jboss"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
